"""
src/groqClient.py — ASCSPipeline Groq API Client
=================================================
Handles all communication with the Groq API.
Builds structured prompts combining the contract code, tool outputs,
and RAG context. Uses the SecurityAuditor persona as the system prompt.

Author: ASCSPipeline
Coding style: camelCase, minimal underscores
"""

from groq import Groq
from typing import Optional


# ── Model Configuration ───────────────────────────────────────────────────────

DEFAULT_MODEL = "llama-3.3-70b-versatile"
MAX_TOKENS = 4096
TEMPERATURE = 0.2  # Low temperature for deterministic, factual security output


# ── System Prompt (SecurityAuditor Persona) ───────────────────────────────────

SECURITY_AUDITOR_SYSTEM_PROMPT = """You are an elite Smart Contract Security Auditor with 10+ years of experience
auditing DeFi protocols managing billions of dollars in assets. You have deep mastery of:
- EVM execution model, opcodes, storage layout
- The SWC (Smart Contract Weakness Classification) registry
- Slither and Aderyn static analysis tool output interpretation
- Reentrancy, integer overflow, access control failures, oracle manipulation, flash loans,
  tx.origin misuse, unprotected selfdestruct, DoS patterns, and proxy vulnerabilities

Your task is to produce a professional security audit report in Markdown format.

STRICT RULES:
1. ONLY report findings that are genuinely present in the code or supported by tool output.
2. Aggressively filter false positives. Do not report speculative issues.
3. Triage tool output rigorously — tools often report noise. Trust your code analysis.
4. For every real finding, provide:
   - Severity level (one of: Critical / High / Medium / Low / Informational)
   - A concise vulnerability name
   - A realistic exploit scenario (3–5 sentences, written as an attack narrative)
   - A secure Solidity code fix (minimal, correct, and well-commented)
5. Structure your entire response as a single, well-formatted Markdown document.
6. Never hallucinate issues that are not supported by the evidence.
7. If the contract is genuinely safe, say so professionally — do not invent findings.
"""


# ── Prompt Builder ────────────────────────────────────────────────────────────

def buildAuditPrompt(
    contractCode: str,
    slitherOutput: str,
    aderynOutput: str,
    ragContext: str,
) -> str:
    """
    Constructs the user-turn prompt for the Groq audit request.

    Combines:
      - The raw Solidity source code
      - Slither's findings summary
      - Aderyn's findings summary
      - Relevant RAG context from the knowledge base

    Returns:
        A fully-formed prompt string.
    """
    prompt = f"""## Smart Contract Code Under Audit

```solidity
{contractCode[:8000]}
```

---

## Slither Static Analysis Output

```
{slitherOutput[:3000]}
```

---

## Aderyn Static Analysis Output

```
{aderynOutput[:2000]}
```

---

## Relevant Vulnerability Knowledge Base Context

{ragContext[:2000]}

---

## Your Task

Analyze the contract code above using the tool outputs and knowledge base context.
Produce a comprehensive security audit report in the following Markdown format:

---

# ASCSPipeline Security Audit Report

## Executive Summary
[2–3 sentence overview of the contract's purpose and overall security posture]

## Risk Rating
| Category | Rating |
|---|---|
| Overall Risk | Critical / High / Medium / Low / Safe |
| Code Quality | Excellent / Good / Fair / Poor |
| Test Coverage Indicators | [observations] |

## Findings

For each finding, use this format:

### [SEVERITY] Finding Name

**Severity**: Critical / High / Medium / Low / Informational
**SWC ID**: SWC-XXX (if applicable)
**Affected Code**: `functionName()` at line X

**Description**:
[Clear technical explanation of the vulnerability]

**Exploit Scenario**:
[Realistic 3–5 sentence attack narrative. Name the attacker "Mallory" and the victim "Alice" or the protocol.]

**Recommended Fix**:
```solidity
// Secure version of the affected code
```

---

## Summary Table

| # | Severity | Finding | Status |
|---|---|---|---|
| 1 | High | Finding Name | Confirmed |

---

## Disclaimer
This report was generated by ASCSPipeline using automated static analysis (Slither, Aderyn)
augmented by AI reasoning. It does not constitute a full manual audit. Always engage a
professional auditor before deploying to mainnet.
"""
    return prompt


# ── Groq API Client ───────────────────────────────────────────────────────────

def generateReport(
    apiKey: str,
    contractCode: str,
    slitherOutput: str,
    aderynOutput: str,
    ragContext: str,
    model: str = DEFAULT_MODEL,
) -> str:
    """
    Sends the audit prompt to the Groq API and returns the full Markdown report.

    Args:
        apiKey:         User-provided Groq API key.
        contractCode:   Raw Solidity source code.
        slitherOutput:  Text summary from Slither analysis.
        aderynOutput:   Text summary from Aderyn analysis.
        ragContext:     Retrieved context from the FAISS RAG engine.
        model:          Groq model identifier.

    Returns:
        Formatted Markdown audit report string.

    Raises:
        ValueError: If the API key is invalid or empty.
        RuntimeError: If the Groq API call fails.
    """
    if not apiKey or not apiKey.strip():
        raise ValueError("A valid Groq API key is required. Please enter it in the sidebar.")

    client = Groq(api_key=apiKey.strip())

    userPrompt = buildAuditPrompt(
        contractCode=contractCode,
        slitherOutput=slitherOutput,
        aderynOutput=aderynOutput,
        ragContext=ragContext,
    )

    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": SECURITY_AUDITOR_SYSTEM_PROMPT},
                {"role": "user", "content": userPrompt},
            ],
            max_tokens=MAX_TOKENS,
            temperature=TEMPERATURE,
        )
        return response.choices[0].message.content

    except Exception as err:
        errorMsg = str(err)
        if "401" in errorMsg or "authentication" in errorMsg.lower():
            raise RuntimeError(
                "Groq authentication failed. Please check your API key in the sidebar."
            ) from err
        elif "rate_limit" in errorMsg.lower():
            raise RuntimeError(
                "Groq rate limit exceeded. Please wait a moment and try again."
            ) from err
        else:
            raise RuntimeError(f"Groq API error: {errorMsg}") from err
